version: "3"                                                                    
services:   
  pfeffernusse:                                                                 
    image: usgsastro/pfeffernusse                                                
    ports:                                                                    
      - "8081:5000"                                                         
    volumes:                                                                  
      - "${SPICE_DATA_DIR}:/data/spice"

  gitlfs:
    image: jlaura/gogitlfs
    ports:
      - "8086:9999"
    volumes:
      - "${LFS_DATA_DIR}:/data"

