version: "3"                                                                    
services:   
  pfeffernusse:                                                                 
    image: jlaura/pfeffernusse                                                
    ports:                                                                    
      - "38002:5000"                                                         
    volumes:                                                                  
      - "/data/big/spice:/data/spice"

  gitlfs:
    image: jlaura/gogitlfs
    ports:
      - "9999:9999"
    volumes:
      - "/data/big/lfs:/data"
