version: "3"                                                                    
services:   
  pfeffernusse:                                                                 
    image: jlaura/pfeffernusse                                                
    ports:                                                                    
      - "38002:5000"                                                         
    volumes:                                                                  
      - "${SPICE_DATA_DIR}:/data/spice"
